### ISSUE TITLE
sqlite3_load_extension is SAD

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/go-whosonfirst-sqlite-geojson#3]
From the `gomod` branch:

```
> ./bin/wof-spatialite-geojson-index -mode repo -timings -dsn flights.db /usr/local/data/sfomuseum-data-flights-2019-08/
fatal error: unexpected signal during runtime execution
[signal SIGFPE: floating-point exception code=0x7 addr=0x5746191 pc=0x5746191]

runtime stack:
runtime.throw(0x4787436, 0x2a)
	/usr/local/go/src/runtime/panic.go:617 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:374 +0x4a9

goroutine 1 [syscall]:
runtime.cgocall(0x450e5e0, 0xc000114eb0, 0xc000114e68)
	/usr/local/go/src/runtime/cgocall.go:128 +0x5b fp=0xc000114e80 sp=0xc000114e48 pc=0x400491b
github.com/mattn/go-sqlite3._Cfunc_sqlite3_load_extension(0x5005fc0, 0x5008530, 0x5008120, 0x0, 0x0)
	_cgo_gotypes.go:935 +0x4d fp=0xc000114eb0 sp=0xc000114e80 pc=0x414f3ed
github.com/mattn/go-sqlite3.(*SQLiteConn).LoadExtension.func5(0xc0000b0600, 0x5008530, 0x5008120, 0xc000114f38)
```

**Comment by saranrapjs** [comment]
This is probably no longer something you're running into, but I found this old issue & have since figured out how to address it! I'm not sure why this is go.mod specific, but if you build using `go build -tags libsqlite3`, this will link against the copy of sqlite that's not the system provided one (which doesn't support extensions). You might need to set some build flag environment variables too. But once I did this, I no longer got the error you noted here!
